[workspace]
members = ["program", "script"]
resolver = "2"

[workspace.dependencies]
sp1-zkvm = "4.1.2"
alloy-primitives = "0.4.2"
alloy-sol-types = "0.4.2"
anyhow = "1.0.75"
ethers = "2.0.10"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107" 